#ifndef SECC_DEFINE_H
#define SECC_DEFINE_H

#define SECC_EV_CONNECTED       0
#define SECC_STATUS_NOTIFICATION    SECC_EV_CONNECTED + 1
#define SECC_AUTHORIZE              SECC_STATUS_NOTIFICATION + 1
#define SECC_START_TRANSACTION      SECC_AUTHORIZE + 1
#define SECC_STOP_TRANSACTION       SECC_START_TRANSACTION + 1
#define SECC_EV_DISCONNECTED        SECC_STOP_TRANSACTION + 1

#endif